# Generated by Django 4.2.1 on 2023-06-16 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbacksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation', models.CharField(choices=[('Ведущий инспектор судебного участка № 8 Дзержинского судебного района г. Перми', 'Ведущий инспектор судебного участка № 8 Дзержинского судебного района г. Перми'), ('Делопроизводитель судебного участка № 1 Дзержинского судебного района г. Перми', 'Делопроизводитель судебного участка № 1 Дзержинского судебного района г. Перми'), ('Секретарь суда сектора делопроизводства судебных участков Дзержинского судебного района г. Перми', 'Секретарь суда сектора делопроизводства судебных участков Дзержинского судебного района г. Перми'), ('Заведующий сектором, секретарь суда сектора делопроизводства судебных участков Дзержинского судебного района г. Перми', 'Заведующий сектором, секретарь суда сектора делопроизводства судебных участков Дзержинского судебного района г. Перми'), ('Помощник мирового судьи судебного участка № 1 Индустриального судебного района г. Перми', 'Помощник мирового судьи судебного участка № 1 Индустриального судебного района г. Перми')], max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('middlename', models.CharField(max_length=250)),
                ('surrname', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
                ('emails', models.EmailField(max_length=254)),
                ('date_ofbirth', models.CharField(max_length=50)),
                ('residential_address', models.CharField(max_length=250)),
                ('criminal_record', models.CharField(choices=[('0', 'Да'), ('1', 'Нет')], default='0', max_length=3)),
                ('description', models.CharField(max_length=250)),
                ('response_status', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancys',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-pub_date',),
            },
        ),
    ]
