# Generated by Django 4.2.1 on 2023-05-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('middlename', models.CharField(max_length=250)),
                ('surrname', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
                ('emails', models.EmailField(max_length=254)),
                ('pasport_number', models.IntegerField()),
                ('pasport_series', models.IntegerField()),
                ('url_linc', models.URLField()),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
