# Generated by Django 4.2.1 on 2023-06-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=250)),
                ('test_log', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='asd',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancys'},
        ),
    ]
