# Generated by Django 4.2.1 on 2023-06-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacksmodel',
            name='criminal_record',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='1', max_length=3),
        ),
    ]
