# Generated by Django 4.2.1 on 2023-06-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startform', '0002_alter_feedbacksmodel_criminal_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
