# Generated by Django 4.2.1 on 2023-06-18 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startform', '0004_post_question_alter_feedbacksmodel_criminal_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='response_status',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbacksmodel',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacksmodel',
            name='response_status',
            field=models.TextField(),
        ),
    ]
