# Generated by Django 4.2.1 on 2023-06-18 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startform', '0005_post_response_status_alter_feedbacksmodel_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emails',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
