# Generated by Django 4.2.1 on 2023-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startform', '0007_post_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacksmodel',
            name='criminal_record',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=250),
        ),
        migrations.AlterField(
            model_name='feedbacksmodel',
            name='surrname',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
