# Generated by Django 4.2.1 on 2023-06-21 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startform', '0008_alter_feedbacksmodel_criminal_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='response_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
